### PR TITLE
Switching the Role and the Principal

### PR DESCRIPTION
**Pull request by alessandrobologna**
as it appears that now they are in inverse order

### CODE REVIEW

**Comment by gtclaancom** [comment]
Hi Alessandro,
Thanks for your pull request. 

Have you tested your code locally? Me and my team are using the Chrome plugin extensively and it is working as expected. So in our case the Principal (saml-provider) comes first and second is the Role. Apparently in your case these are switched around (role comes first).

What I think is the case is that the order of the Principal and the Role in the SAML assertion depends on the configuration of the SAML IDP (e.g. ADFS, Shibboleth). What I could do is change the code by using a regex to search for the Principal and Role. That way the order does not matter anymore.

Would that be OK? I expect to have some time to fix this somewhere next week.

**Comment by gtclaancom** [comment]
Hi Alessandro,
I just changed the code. Version 1.2 of the Chrome plugin is now uploaded to the Chrome Web Store. If you have the extension still installed it will be auto updated. I use a regex to extract the Role and Principal  so now it should also work for you. Please feel free to drop me some feedback. Thanks.

Cheers!
Gerard

**Comment by alessandrobologna** [comment]
Hi Gerard,
yes, we are google apps and maybe it's a different case. Yours is great solution, thank you!

**Comment by gtclaancom** [comment]
Since version 1.2 solved this issue I am closing the pull request.
Thanks again for your feedback.
Best regards,
Gerard

**Pull request closed without merging**
